name: Atualizar Malha RPL CGNA

on:
  schedule:
    # Roda toda quinta-feira às 03:00 UTC
    - cron: '0 3 * * 4'
  workflow_dispatch: # Permite rodar manualmente no botão "Run workflow"

jobs:
  atualizar-dados:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas
        run: pip install requests beautifulsoup4

      - name: Executar script de download
        run: python scripts/update_rpl.py

      - name: Commit e Push das alterações
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Atualização automática do ciclo RPL via CGNA"
          branch: main
          file_pattern: "*.txt" # Commit apenas nos arquivos TXT